'use strict';

const fs = require('node:fs/promises');
const path = require('path');
const debug = require('debug')('WireGuard');
const crypto = require('node:crypto');
const zlib = require('node:zlib');
const QRCode = require('qrcode');
const CRC32 = require('crc-32');

const Util = require('./Util');
const Awg = require('./Awg');
const ServerError = require('./ServerError');

const {
  WG_PATH,
  WG_HOST,
  WG_PORT,
  WG_CONFIG_PORT,
  WG_MTU,
  WG_DEFAULT_DNS,
  WG_DEFAULT_ADDRESS,
  WG_PERSISTENT_KEEPALIVE,
  WG_ALLOWED_IPS,
  WG_PRE_UP,
  WG_POST_UP,
  WG_PRE_DOWN,
  WG_POST_DOWN,
  WG_ENABLE_EXPIRES_TIME,
  WG_ENABLE_ONE_TIME_LINKS,
  AWG_PROFILE,
  AWG_ENV,
  AWGGO_VERSION,
  AWGTOOLS_VERSION,
} = require('../config');

const formatAwgErrors = (errors) => Object.entries(errors)
  .map(([key, message]) => `${key}: ${message}`)
  .join('; ');

// Parameters for a new installation: generated profile + env overrides.
const initialAwgParams = () => {
  const params = Awg.generate(AWG_PROFILE);
  for (const [key, value] of Object.entries(Awg.normalize(AWG_ENV))) {
    if (value !== null) params[key] = value;
  }

  const errors = Awg.validate(params);
  if (Object.keys(errors).length > 0) {
    throw new Error(`Invalid AmneziaWG environment parameters: ${formatAwgErrors(errors)}`);
  }

  return params;
};

module.exports = class WireGuard {

  async __buildConfig() {
    this.__configPromise = Promise.resolve().then(async () => {
      if (!WG_HOST) {
        throw new Error('WG_HOST Environment Variable Not Set!');
      }

      debug('Loading configuration...');
      let config;
      try {
        config = await fs.readFile(path.join(WG_PATH, 'wg0.json'), 'utf8');
        config = JSON.parse(config);
        this.__upgradeConfig(config);
        debug('Configuration loaded.');
      } catch (err) {
        // Only generate a new config when there is none: a broken wg0.json
        // must not be silently replaced, it holds all clients.
        if (err.code !== 'ENOENT') throw err;

        const privateKey = await Util.exec('awg genkey');
        const publicKey = await Util.exec(`echo ${privateKey} | awg pubkey`, {
          log: 'echo ***hidden*** | awg pubkey',
        });
        const address = WG_DEFAULT_ADDRESS.replace('x', '1');

        config = {
          server: {
            privateKey,
            publicKey,
            address,
            ...initialAwgParams(),
          },
          clients: {},
        };
        debug(`Configuration generated (AmneziaWG profile ${AWG_PROFILE}).`);
      }

      return config;
    });

    return this.__configPromise;
  }

  // Configs from older versions (AWG 1.0) only have jc..h4: bring values to
  // their stored types, the missing parameters become null (off).
  __upgradeConfig(config) {
    Object.assign(config.server, Awg.normalize(config.server));
    const errors = Awg.validate(config.server);
    if (Object.keys(errors).length > 0) {
      debug(`Warning: invalid AmneziaWG parameters in wg0.json: ${formatAwgErrors(errors)}`);
    }
  }

  async __upInterface() {
    await Util.exec('awg-quick down wg0').catch(() => {});
    await Util.exec('awg-quick up wg0').catch((err) => {
      if (err && err.message && err.message.includes('Cannot find device "wg0"')) {
        throw new Error('AmneziaWG exited with the error: Cannot find device "wg0"\nThis usually means that /dev/net/tun is not available in the container!');
      }

      throw err;
    });
  }

  async getConfig() {
    if (!this.__configPromise) {
      const config = await this.__buildConfig();

      await this.__saveConfig(config);
      await this.__upInterface();
      // await Util.exec(`iptables -t nat -A POSTROUTING -s ${WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ' + WG_DEVICE + ' -j MASQUERADE`);
      // await Util.exec('iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT');
      // await Util.exec('iptables -A FORWARD -i wg0 -j ACCEPT');
      // await Util.exec('iptables -A FORWARD -o wg0 -j ACCEPT');
      await this.__syncConfig();
    }

    return this.__configPromise;
  }

  async saveConfig() {
    const config = await this.getConfig();
    await this.__saveConfig(config);
    await this.__syncConfig();
  }

  async __saveConfig(config) {
    let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = ${WG_PORT}
PreUp = ${WG_PRE_UP}
PostUp = ${WG_POST_UP}
PreDown = ${WG_PRE_DOWN}
PostDown = ${WG_POST_DOWN}
${Awg.interfaceLines(config.server, 'server')}
`;

    for (const [clientId, client] of Object.entries(config.clients)) {
      if (!client.enabled) continue;

      result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${client.address}/32`;
    }

    debug('Config saving...');
    await fs.writeFile(path.join(WG_PATH, 'wg0.json'), JSON.stringify(config, false, 2), {
      mode: 0o660,
    });
    await fs.writeFile(path.join(WG_PATH, 'wg0.conf'), result, {
      mode: 0o600,
    });
    debug('Config saved.');
  }

  async __syncConfig() {
    debug('Config syncing...');
    await Util.exec('awg syncconf wg0 <(awg-quick strip wg0)');
    debug('Config synced.');
  }

  async getClients() {
    const config = await this.getConfig();
    const clients = Object.entries(config.clients).map(([clientId, client]) => ({
      id: clientId,
      name: client.name,
      enabled: client.enabled,
      address: client.address,
      publicKey: client.publicKey,
      createdAt: new Date(client.createdAt),
      updatedAt: new Date(client.updatedAt),
      expiredAt: client.expiredAt
        ? new Date(client.expiredAt)
        : null,
      deleteOnExpire: client.deleteOnExpire === true,
      allowedIPs: client.allowedIPs,
      oneTimeLink: client.oneTimeLink ?? null,
      oneTimeLinkExpiresAt: client.oneTimeLinkExpiresAt ?? null,
      downloadableConfig: 'privateKey' in client,
      persistentKeepalive: null,
      latestHandshakeAt: null,
      transferRx: null,
      transferTx: null,
      endpoint: null,
    }));

    // Loop WireGuard status. The interface line (AWG parameters, I1-I5 may
    // contain spaces) is skipped; peer lines keep the WireGuard layout.
    const dump = await Util.exec('awg show wg0 dump', {
      log: false,
    });
    dump
      .trim()
      .split('\n')
      .slice(1)
      .forEach((line) => {
        const [
          publicKey,
          preSharedKey, // eslint-disable-line no-unused-vars
          endpoint, // eslint-disable-line no-unused-vars
          allowedIps, // eslint-disable-line no-unused-vars
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = line.split('\t');

        const client = clients.find((client) => client.publicKey === publicKey);
        if (!client) return;

        client.latestHandshakeAt = latestHandshakeAt === '0'
          ? null
          : new Date(Number(`${latestHandshakeAt}000`));
        client.endpoint = endpoint === '(none)' ? null : endpoint;
        client.transferRx = Number(transferRx);
        client.transferTx = Number(transferTx);
        client.persistentKeepalive = persistentKeepalive;
      });

    return clients;
  }

  async getClient({ clientId }) {
    const config = await this.getConfig();
    const client = config.clients[clientId];
    if (!client) {
      throw new ServerError(`Client Not Found: ${clientId}`, 404);
    }

    return client;
  }

  async getClientConfiguration({ clientId }) {
    const config = await this.getConfig();
    const client = await this.getClient({ clientId });

    return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}/24
${WG_DEFAULT_DNS ? `DNS = ${WG_DEFAULT_DNS}\n` : ''}\
${WG_MTU ? `MTU = ${WG_MTU}\n` : ''}\
${Awg.interfaceLines(config.server, 'client')}

[Peer]
PublicKey = ${config.server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${WG_ALLOWED_IPS}
PersistentKeepalive = ${config.server.persistentKeepalive ?? WG_PERSISTENT_KEEPALIVE}
Endpoint = ${WG_HOST}:${WG_CONFIG_PORT}`;
  }

  async getClientQRCodeSVG({ clientId }) {
    const config = await this.getClientConfiguration({ clientId });
    return QRCode.toString(config, {
      type: 'svg',
      width: 512,
    });
  }

  /**
   * vpn:// link for the AmneziaVPN app: base64url of qCompress()ed JSON
   * (4-byte big-endian length + zlib). The JSON mirrors what AmneziaVPN
   * builds itself when it imports a native AmneziaWG .conf.
   */
  async getClientVpnLink({ clientId }) {
    const config = await this.getConfig();
    const client = await this.getClient({ clientId });
    if (!client.privateKey) {
      throw new ServerError('This client has no private key', 400);
    }

    const params = Awg.normalize(config.server);
    const lastConfig = {
      config: await this.getClientConfiguration({ clientId }),
      hostName: WG_HOST,
      port: Number(WG_CONFIG_PORT),
      client_priv_key: client.privateKey,
      client_ip: `${client.address}/24`,
      server_pub_key: config.server.publicKey,
      ...(client.preSharedKey ? { psk_key: client.preSharedKey } : {}),
      persistent_keep_alive: String(params.persistentKeepalive ?? WG_PERSISTENT_KEEPALIVE),
      allowed_ips: WG_ALLOWED_IPS.split(',').map((ip) => ip.trim()).filter(Boolean),
      mtu: WG_MTU || '1376',
      ...Awg.interfaceFields(params, 'client'),
    };

    const vpnConfig = {
      containers: [{
        container: 'amnezia-awg',
        awg: {
          last_config: JSON.stringify(lastConfig),
          isThirdPartyConfig: true,
          port: String(WG_CONFIG_PORT),
          transport_proto: 'udp',
        },
      }],
      defaultContainer: 'amnezia-awg',
      description: client.name,
      hostName: WG_HOST,
    };
    const dns = (WG_DEFAULT_DNS || '').split(',').map((ip) => ip.trim()).filter(Boolean);
    if (dns.length > 0) {
      vpnConfig.dns1 = dns[0];
      vpnConfig.dns2 = dns[1] || dns[0];
    }

    const json = Buffer.from(JSON.stringify(vpnConfig));
    const length = Buffer.alloc(4);
    length.writeUInt32BE(json.length);
    const compressed = Buffer.concat([length, zlib.deflateSync(json, { level: 8 })]);
    return `vpn://${compressed.toString('base64url')}`;
  }

  async createClient({
    name, expiredDate, expiresAt, deleteOnExpire,
  }) {
    if (!name) {
      throw new Error('Missing: Name');
    }

    const config = await this.getConfig();

    const privateKey = await Util.exec('awg genkey');
    const publicKey = await Util.exec(`echo ${privateKey} | awg pubkey`, {
      log: 'echo ***hidden*** | awg pubkey',
    });
    const preSharedKey = await Util.exec('awg genpsk');

    // Calculate next IP
    let address;
    for (let i = 2; i < 255; i++) {
      const client = Object.values(config.clients).find((client) => {
        return client.address === WG_DEFAULT_ADDRESS.replace('x', i);
      });

      if (!client) {
        address = WG_DEFAULT_ADDRESS.replace('x', i);
        break;
      }
    }

    if (!address) {
      throw new Error('Maximum number of clients reached.');
    }
    // Create Client
    const id = crypto.randomUUID();
    const client = {
      id,
      name,
      address,
      privateKey,
      publicKey,
      preSharedKey,

      createdAt: new Date(),
      updatedAt: new Date(),
      expiredAt: null,
      deleteOnExpire: false,
      enabled: true,
    };
    if (expiresAt) {
      // Exact moment (temporary configs: 1 hour, 1 day, custom date and time)
      client.expiredAt = new Date(expiresAt);
      if (Number.isNaN(client.expiredAt.getTime())) {
        throw new ServerError(`Invalid expiration date: ${expiresAt}`, 400);
      }
    } else if (expiredDate) {
      client.expiredAt = new Date(expiredDate);
      client.expiredAt.setHours(23);
      client.expiredAt.setMinutes(59);
      client.expiredAt.setSeconds(59);
    }
    client.deleteOnExpire = client.expiredAt !== null && deleteOnExpire === true;
    config.clients[id] = client;

    await this.saveConfig();

    return client;
  }

  async deleteClient({ clientId }) {
    const config = await this.getConfig();

    if (config.clients[clientId]) {
      delete config.clients[clientId];
      await this.saveConfig();
    }
  }

  async enableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = true;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async generateOneTimeLink({ clientId }) {
    const client = await this.getClient({ clientId });
    const key = `${clientId}-${Math.floor(Math.random() * 1000)}`;
    client.oneTimeLink = Math.abs(CRC32.str(key)).toString(16);
    client.oneTimeLinkExpiresAt = new Date(Date.now() + 5 * 60 * 1000);
    client.updatedAt = new Date();
    await this.saveConfig();
  }

  async eraseOneTimeLink({ clientId }) {
    const client = await this.getClient({ clientId });
    // client.oneTimeLink = null;
    client.oneTimeLinkExpiresAt = new Date(Date.now() + 10 * 1000);
    client.updatedAt = new Date();
    await this.saveConfig();
  }

  async disableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = false;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientName({ clientId, name }) {
    const client = await this.getClient({ clientId });

    client.name = name;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientAddress({ clientId, address }) {
    const client = await this.getClient({ clientId });

    if (!Util.isValidIPv4(address)) {
      throw new ServerError(`Invalid Address: ${address}`, 400);
    }

    client.address = address;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  /**
   * Changes when a client expires. `expiresAt` is an exact moment (null =
   * permanent); the legacy `expireDate` is a day (expires at 23:59:59).
   * A client that was disabled because it had expired is enabled again when
   * it gets a lifetime that has not passed yet.
   */
  async updateClientExpireDate({
    clientId, expireDate, expiresAt, deleteOnExpire,
  }) {
    const client = await this.getClient({ clientId });
    const now = new Date();
    const wasExpired = !!client.expiredAt && new Date(client.expiredAt) <= now;

    if (expiresAt !== undefined) {
      client.expiredAt = expiresAt === null ? null : new Date(expiresAt);
      if (client.expiredAt !== null && Number.isNaN(client.expiredAt.getTime())) {
        throw new ServerError(`Invalid expiration date: ${expiresAt}`, 400);
      }
    } else if (expireDate) {
      client.expiredAt = new Date(expireDate);
      client.expiredAt.setHours(23);
      client.expiredAt.setMinutes(59);
      client.expiredAt.setSeconds(59);
    } else {
      client.expiredAt = null;
    }

    if (deleteOnExpire !== undefined) client.deleteOnExpire = deleteOnExpire === true;
    if (client.expiredAt === null) client.deleteOnExpire = false;

    if (!client.enabled && wasExpired && (client.expiredAt === null || client.expiredAt > now)) {
      debug(`Client ${clientId} got a new lifetime, enabling it again.`);
      client.enabled = true;
    }
    client.updatedAt = now;

    await this.saveConfig();
  }

  // A restored backup may carry other AmneziaWG parameters. syncconf cannot
  // unset interface parameters (e.g. HeaderProtectionKey), so restart instead.
  async __reloadConfig() {
    await this.__buildConfig();
    await this.__upInterface();
  }

  async restoreConfiguration(config) {
    debug('Starting configuration restore process.');
    const _config = JSON.parse(config);
    this.__upgradeConfig(_config);
    await this.__saveConfig(_config);
    await this.__reloadConfig();
    debug('Configuration restore process completed.');
  }

  async backupConfiguration() {
    debug('Starting configuration backup.');
    const config = await this.getConfig();
    const backup = JSON.stringify(config, null, 2);
    debug('Configuration backup completed.');
    return backup;
  }

  async getAwgSettings() {
    const config = await this.getConfig();
    const params = Awg.normalize(config.server);
    return {
      params,
      profile: Awg.detectProfile(params),
      defaultPersistentKeepalive: WG_PERSISTENT_KEEPALIVE,
      versions: {
        amneziawgGo: AWGGO_VERSION,
        amneziawgTools: AWGTOOLS_VERSION,
      },
    };
  }

  async generateAwgSettings({ profile }) {
    if (!Awg.PROFILES.includes(profile)) {
      throw new ServerError(`Unknown AmneziaWG profile: ${profile}`, 400);
    }
    return Awg.generate(profile);
  }

  /**
   * Validates and applies new AmneziaWG parameters.
   * Returns { errors } (per field) when the input is invalid, { error } when
   * AmneziaWG refused the parameters, {} on success. The interface is
   * restarted, since syncconf cannot unset interface parameters; if it fails
   * to come up, the previous parameters are restored.
   */
  async updateAwgSettings(input) {
    const params = Awg.normalize(input);
    const errors = Awg.validate(params);
    if (Object.keys(errors).length > 0) {
      return { errors };
    }

    const config = await this.getConfig();
    const previous = Awg.normalize(config.server);
    Object.assign(config.server, params);

    try {
      await this.__saveConfig(config);
      await this.__upInterface();
    } catch (err) {
      debug(`Failed to apply AmneziaWG parameters, rolling back: ${err.message}`);
      Object.assign(config.server, previous);
      await this.__saveConfig(config);
      await this.__upInterface();
      return { error: `AmneziaWG rejected the parameters: ${err.message}` };
    }

    debug('AmneziaWG parameters updated.');
    return {};
  }

  // Shutdown wireguard
  async Shutdown() {
    await Util.exec('awg-quick down wg0').catch(() => {});
  }

  async cronJobEveryMinute() {
    const config = await this.getConfig();
    let needSaveConfig = false;
    // Expires Feature
    if (WG_ENABLE_EXPIRES_TIME === 'true') {
      for (const [clientId, client] of Object.entries(config.clients)) {
        if (!client.expiredAt || new Date() <= new Date(client.expiredAt)) continue;
        if (client.deleteOnExpire === true) {
          debug(`Client ${clientId} expired, deleting.`);
          needSaveConfig = true;
          delete config.clients[clientId];
        } else if (client.enabled === true) {
          debug(`Client ${clientId} expired.`);
          needSaveConfig = true;
          client.enabled = false;
          client.updatedAt = new Date();
        }
      }
    }
    // One Time Link Feature
    if (WG_ENABLE_ONE_TIME_LINKS === 'true') {
      for (const client of Object.values(config.clients)) {
        if (client.oneTimeLink !== null && new Date() > new Date(client.oneTimeLinkExpiresAt)) {
          debug(`Client ${client.id} One Time Link expired.`);
          needSaveConfig = true;
          client.oneTimeLink = null;
          client.oneTimeLinkExpiresAt = null;
          client.updatedAt = new Date();
        }
      }
    }
    if (needSaveConfig) {
      await this.saveConfig();
    }
  }

  async getMetrics() {
    const clients = await this.getClients();
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    let wireguardSentBytes = '';
    let wireguardReceivedBytes = '';
    let wireguardLatestHandshakeSeconds = '';
    for (const client of Object.values(clients)) {
      wireguardPeerCount++;
      if (client.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (client.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
      wireguardSentBytes += `wireguard_sent_bytes{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${Number(client.transferTx)}\n`;
      wireguardReceivedBytes += `wireguard_received_bytes{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${Number(client.transferRx)}\n`;
      wireguardLatestHandshakeSeconds += `wireguard_latest_handshake_seconds{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${client.latestHandshakeAt ? (new Date().getTime() - new Date(client.latestHandshakeAt).getTime()) / 1000 : 0}\n`;
    }

    let returnText = '# HELP wg-easy and wireguard metrics\n';

    returnText += '\n# HELP wireguard_configured_peers\n';
    returnText += '# TYPE wireguard_configured_peers gauge\n';
    returnText += `wireguard_configured_peers{interface="wg0"} ${Number(wireguardPeerCount)}\n`;

    returnText += '\n# HELP wireguard_enabled_peers\n';
    returnText += '# TYPE wireguard_enabled_peers gauge\n';
    returnText += `wireguard_enabled_peers{interface="wg0"} ${Number(wireguardEnabledPeersCount)}\n`;

    returnText += '\n# HELP wireguard_connected_peers\n';
    returnText += '# TYPE wireguard_connected_peers gauge\n';
    returnText += `wireguard_connected_peers{interface="wg0"} ${Number(wireguardConnectedPeersCount)}\n`;

    returnText += '\n# HELP wireguard_sent_bytes Bytes sent to the peer\n';
    returnText += '# TYPE wireguard_sent_bytes counter\n';
    returnText += `${wireguardSentBytes}`;

    returnText += '\n# HELP wireguard_received_bytes Bytes received from the peer\n';
    returnText += '# TYPE wireguard_received_bytes counter\n';
    returnText += `${wireguardReceivedBytes}`;

    returnText += '\n# HELP wireguard_latest_handshake_seconds UNIX timestamp seconds of the last handshake\n';
    returnText += '# TYPE wireguard_latest_handshake_seconds gauge\n';
    returnText += `${wireguardLatestHandshakeSeconds}`;

    return returnText;
  }

  async getMetricsJSON() {
    const clients = await this.getClients();
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    for (const client of Object.values(clients)) {
      wireguardPeerCount++;
      if (client.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (client.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
    }
    return {
      wireguard_configured_peers: Number(wireguardPeerCount),
      wireguard_enabled_peers: Number(wireguardEnabledPeersCount),
      wireguard_connected_peers: Number(wireguardConnectedPeersCount),
    };
  }

};
